import { LoanProduct } from "./types";

export async function getMockProducts(): Promise<LoanProduct[]> {
  // In production, this would fetch from Supabase
  // For now, return mock data
  return [
    {
      id: "1",
      name: "Premium Personal Loan",
      description: "Flexible personal loan with competitive rates for qualified borrowers. Perfect for debt consolidation, home improvements, or major purchases.",
      interestRate: 4.5,
      minAmount: 5000,
      maxAmount: 100000,
      minTermMonths: 12,
      maxTermMonths: 84,
      eligibilityScore: 92,
      category: "personal",
      features: ["No prepayment penalty", "Fast approval", "Online application", "Flexible repayment"],
      requirements: ["Credit score 680+", "Annual income ₹50,000+", "Valid ID"],
      isPreApproved: true,
      processingTime: "24 hours",
      maxLtv: null,
      creditScoreMin: 680,
      incomeMin: 50000,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "2",
      name: "Home Equity Line of Credit",
      description: "Access your home's equity with a flexible line of credit. Low rates and flexible terms for homeowners.",
      interestRate: 5.2,
      minAmount: 10000,
      maxAmount: 500000,
      minTermMonths: 60,
      maxTermMonths: 360,
      eligibilityScore: 88,
      category: "home",
      features: ["Low interest rate", "Flexible draw period", "Tax benefits", "No closing costs"],
      requirements: ["Homeowner", "Credit score 650+", "LTV under 80%"],
      isPreApproved: false,
      processingTime: "5-7 business days",
      maxLtv: 80,
      creditScoreMin: 650,
      incomeMin: 60000,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "3",
      name: "Auto Loan Express",
      description: "Quick and easy auto financing with competitive rates. Get pre-approved before you shop.",
      interestRate: 3.9,
      minAmount: 5000,
      maxAmount: 75000,
      minTermMonths: 24,
      maxTermMonths: 84,
      eligibilityScore: 85,
      category: "auto",
      features: ["Pre-approval available", "Competitive rates", "Fast processing", "New and used vehicles"],
      requirements: ["Credit score 600+", "Valid driver's license", "Vehicle information"],
      isPreApproved: true,
      processingTime: "Same day",
      maxLtv: 100,
      creditScoreMin: 600,
      incomeMin: 30000,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "4",
      name: "Small Business Loan",
      description: "Funding for your business growth. Flexible terms and competitive rates for established businesses.",
      interestRate: 6.5,
      minAmount: 25000,
      maxAmount: 500000,
      minTermMonths: 12,
      maxTermMonths: 120,
      eligibilityScore: 75,
      category: "business",
      features: ["Business growth funding", "Flexible terms", "No prepayment penalty", "Dedicated support"],
      requirements: ["Business 2+ years old", "Annual revenue ₹100,000+", "Business plan"],
      isPreApproved: false,
      processingTime: "7-10 business days",
      maxLtv: null,
      creditScoreMin: 650,
      incomeMin: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "5",
      name: "Student Loan Refinance",
      description: "Lower your student loan payments with competitive refinancing rates. Consolidate multiple loans into one.",
      interestRate: 4.2,
      minAmount: 5000,
      maxAmount: 300000,
      minTermMonths: 60,
      maxTermMonths: 240,
      eligibilityScore: 80,
      category: "student",
      features: ["Lower monthly payments", "Fixed or variable rates", "No origination fee", "Cosigner release"],
      requirements: ["Degree completed", "Credit score 650+", "Employment verification"],
      isPreApproved: false,
      processingTime: "2-3 business days",
      maxLtv: null,
      creditScoreMin: 650,
      incomeMin: 40000,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "6",
      name: "Credit Builder Card",
      description: "Build or rebuild your credit with our secured credit card. Low fees and credit reporting.",
      interestRate: 18.9,
      minAmount: 200,
      maxAmount: 5000,
      minTermMonths: 12,
      maxTermMonths: 60,
      eligibilityScore: 70,
      category: "credit-card",
      features: ["No credit check", "Credit reporting", "Low annual fee", "Credit limit increase"],
      requirements: ["Security deposit", "Valid ID", "Bank account"],
      isPreApproved: false,
      processingTime: "48 hours",
      maxLtv: null,
      creditScoreMin: null,
      incomeMin: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "7",
      name: "Quick Cash Personal Loan",
      description: "Fast access to cash when you need it. Simple application process with quick approval.",
      interestRate: 7.8,
      minAmount: 1000,
      maxAmount: 25000,
      minTermMonths: 6,
      maxTermMonths: 36,
      eligibilityScore: 65,
      category: "personal",
      features: ["Fast approval", "Simple application", "Flexible terms", "No hidden fees"],
      requirements: ["Credit score 580+", "Income verification", "Bank account"],
      isPreApproved: false,
      processingTime: "24 hours",
      maxLtv: null,
      creditScoreMin: 580,
      incomeMin: 25000,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "8",
      name: "Jumbo Mortgage Loan",
      description: "Financing for high-value properties. Competitive rates for qualified borrowers.",
      interestRate: 5.8,
      minAmount: 500000,
      maxAmount: 5000000,
      minTermMonths: 180,
      maxTermMonths: 360,
      eligibilityScore: 82,
      category: "home",
      features: ["High loan amounts", "Competitive rates", "Flexible terms", "Professional service"],
      requirements: ["Credit score 700+", "Down payment 20%+", "Income verification"],
      isPreApproved: false,
      processingTime: "14-21 business days",
      maxLtv: 80,
      creditScoreMin: 700,
      incomeMin: 150000,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];
}

